# coding: utf-8

"""
Yapily API

The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.

The version of the OpenAPI document: 4.2.0
Contact: support@yapily.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from yapily.api.webhooks_api import WebhooksApi  # noqa: E501


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebhooksApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_delete_webhook(self) -> None:
        """Test case for delete_webhook

        Delete Webhook Event  # noqa: E501
        """
        pass

    def test_get_registered_webhooks(self) -> None:
        """Test case for get_registered_webhooks

        Retrieve All Webhook Events  # noqa: E501
        """
        pass

    def test_get_webhook_events_categories(self) -> None:
        """Test case for get_webhook_events_categories

        Get Webhook Categories  # noqa: E501
        """
        pass

    def test_register_webhook(self) -> None:
        """Test case for register_webhook

        Register Webhook Event  # noqa: E501
        """
        pass

    def test_webhook_secret_reset(self) -> None:
        """Test case for webhook_secret_reset

        Reset Webhook Secret  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
