# coding: utf-8

"""
    Yapily API

    The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.

    The version of the OpenAPI document: 4.2.0
    Contact: support@yapily.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from yapily.models.api_list_response_of_direct_debit_response import ApiListResponseOfDirectDebitResponse  # noqa: E501

class TestApiListResponseOfDirectDebitResponse(unittest.TestCase):
    """ApiListResponseOfDirectDebitResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiListResponseOfDirectDebitResponse:
        """Test ApiListResponseOfDirectDebitResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiListResponseOfDirectDebitResponse`
        """
        model = ApiListResponseOfDirectDebitResponse()  # noqa: E501
        if include_optional:
            return ApiListResponseOfDirectDebitResponse(
                meta = yapily.models.response_list_meta.ResponseListMeta(
                    tracing_id = '', 
                    count = 56, 
                    pagination = yapily.models.pagination.Pagination(
                        total_count = 56, 
                        self = yapily.models.filter_and_sort.FilterAndSort(
                            from = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            before = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            limit = 56, 
                            sort = 'date', 
                            offset = 56, 
                            cursor = '', ), 
                        next = yapily.models.next.Next(
                            from = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            before = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            limit = 56, 
                            cursor = '', ), ), ),
                data = [
                    yapily.models.direct_debit_response.DirectDebitResponse(
                        id = '', 
                        status_details = yapily.models.payment_status_details.PaymentStatusDetails(
                            status = 'PENDING', 
                            status_reason = '', 
                            status_reason_description = '', 
                            status_update_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            multi_authorisation_status = yapily.models.multi_authorisation.MultiAuthorisation(
                                number_of_authorisation_required = 56, 
                                number_of_authorisation_received = 56, 
                                last_updated_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                expiration_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                            iso_status = yapily.models.payment_iso_status.PaymentIsoStatus(
                                code = 'ACCC', 
                                name = 'AcceptedCreditSettlementCompleted', ), ), 
                        payee_details = yapily.models.direct_debit_payee.DirectDebitPayee(
                            name = 'Tempus Risus Company', ), 
                        reference = '', 
                        previous_payment_amount = yapily.models.amount_details.Amount Details(
                            amount = 10, 
                            currency = 'GBP', ), 
                        previous_payment_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                links = {
                    'key' : ''
                    },
                forwarded_data = [
                    yapily.models.response_forwarded_data.ResponseForwardedData(
                        headers = {
                            'key' : ''
                            }, 
                        url = '', )
                    ],
                raw = [
                    yapily.models.raw_response.RawResponse(
                        request = yapily.models.raw_request.RawRequest(
                            method = '', 
                            url = '', 
                            request_instant = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            headers = {
                                'key' : ''
                                }, 
                            body = yapily.models.body.body(), 
                            body_parameters = {
                                'key' : ''
                                }, 
                            start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                        duration = '', 
                        headers = {
                            'key' : ''
                            }, 
                        result_code = 56, 
                        result = yapily.models.result.result(), )
                    ],
                paging = yapily.models.filtered_client_payload_list_direct_debit_response.FilteredClientPayloadListDirectDebitResponse(
                    api_call = yapily.models.api_call.ApiCall(), 
                    data = [
                        yapily.models.direct_debit_response.DirectDebitResponse(
                            id = '', 
                            status_details = yapily.models.payment_status_details.PaymentStatusDetails(
                                status = 'PENDING', 
                                status_reason = '', 
                                status_reason_description = '', 
                                status_update_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                multi_authorisation_status = yapily.models.multi_authorisation.MultiAuthorisation(
                                    number_of_authorisation_required = 56, 
                                    number_of_authorisation_received = 56, 
                                    last_updated_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    expiration_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                                iso_status = yapily.models.payment_iso_status.PaymentIsoStatus(
                                    code = 'ACCC', 
                                    name = 'AcceptedCreditSettlementCompleted', ), ), 
                            payee_details = yapily.models.direct_debit_payee.DirectDebitPayee(
                                name = 'Tempus Risus Company', ), 
                            reference = '', 
                            previous_payment_amount = yapily.models.amount_details.Amount Details(
                                amount = 10, 
                                currency = 'GBP', ), 
                            previous_payment_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    next_cursor_hash = '', 
                    next_link = '', 
                    paging_map = {
                        'key' : yapily.models.filter_and_sort.FilterAndSort(
                            from = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            before = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            limit = 56, 
                            sort = 'date', 
                            offset = 56, 
                            cursor = '', )
                        }, 
                    total_count = 56, ),
                tracing_id = ''
            )
        else:
            return ApiListResponseOfDirectDebitResponse(
        )
        """

    def testApiListResponseOfDirectDebitResponse(self):
        """Test ApiListResponseOfDirectDebitResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
