# coding: utf-8

"""
    Yapily API

    The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.  # noqa: E501

    The version of the OpenAPI document: 2.13.1
    Contact: support@yapily.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import yapily
from yapily.models.api_list_response_of_virtual_account import ApiListResponseOfVirtualAccount  # noqa: E501
from yapily.rest import ApiException

class TestApiListResponseOfVirtualAccount(unittest.TestCase):
    """ApiListResponseOfVirtualAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ApiListResponseOfVirtualAccount
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = yapily.models.api_list_response_of_virtual_account.ApiListResponseOfVirtualAccount()  # noqa: E501
        if include_optional :
            return ApiListResponseOfVirtualAccount(
                meta = yapily.models.response_list_meta.ResponseListMeta(
                    tracing_id = '0', 
                    count = 56, 
                    pagination = yapily.models.pagination.Pagination(
                        total_count = 56, 
                        self = yapily.models.filter_and_sort.FilterAndSort(
                            from = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            before = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            limit = 56, 
                            sort = 'date', 
                            offset = 56, 
                            cursor = '0', ), 
                        next = yapily.models.next.Next(
                            from = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            before = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            limit = 56, 
                            cursor = '0', ), ), ), 
                links = yapily.models.links.Links(
                    self = '0', 
                    first = '0', 
                    last = '0', 
                    next = '0', 
                    previous = '0', ), 
                data = [
                    yapily.models.virtual_account.VirtualAccount(
                        id = 'eb2ad083-a111-4143-8756-a3a3cef4031c', 
                        created_date_time = '2020-04-24T00:30:19.951Z', 
                        status = 'ACTIVE', 
                        nickname = 'MyAccount123', 
                        currency = 'GBP', 
                        balances = [
                            yapily.models.virtual_account_balance.VirtualAccountBalance(
                                type = 'INTERIM_AVAILABLE', 
                                balance_amount = yapily.models.amount.Amount(
                                    amount = 10, 
                                    currency = 'GBP', ), )
                            ], 
                        bank_account = yapily.models.virtual_account_bank_account.VirtualAccountBankAccount(
                            currency = 'GBP', 
                            bank_name = 'Lloyds Bank', 
                            bank_address = 'WE12 ABC', 
                            bank_country = 'GB', 
                            account_identifications = [{"identification":"401016","type":"SORT_CODE"},{"identification":"71518920","type":"ACCOUNT_NUMBER"}], 
                            pay_in_reference = 'Ref1249944', ), )
                    ], 
                forwarded_data = [
                    yapily.models.response_forwarded_data.ResponseForwardedData(
                        headers = {
                            'key' : '0'
                            }, 
                        url = '0', )
                    ], 
                tracing_id = '0'
            )
        else :
            return ApiListResponseOfVirtualAccount(
        )

    def testApiListResponseOfVirtualAccount(self):
        """Test ApiListResponseOfVirtualAccount"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
