# coding: utf-8

"""
    Yapily API

    The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.

    The version of the OpenAPI document: 2.25.0
    Contact: support@yapily.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from yapily.api.virtual_accounts_beneficiaries_api import VirtualAccountsBeneficiariesApi  # noqa: E501


class TestVirtualAccountsBeneficiariesApi(unittest.TestCase):
    """VirtualAccountsBeneficiariesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VirtualAccountsBeneficiariesApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create_virtual_account_beneficiary(self) -> None:
        """Test case for create_virtual_account_beneficiary

        Create Beneficiary  # noqa: E501
        """
        pass

    def test_delete_virtual_account_beneficiary(self) -> None:
        """Test case for delete_virtual_account_beneficiary

        Delete Beneficiary  # noqa: E501
        """
        pass

    def test_get_virtual_account_beneficiaries(self) -> None:
        """Test case for get_virtual_account_beneficiaries

        Get List Of Beneficiaries  # noqa: E501
        """
        pass

    def test_get_virtual_account_beneficiary(self) -> None:
        """Test case for get_virtual_account_beneficiary

        Get Beneficiary  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
