# coding: utf-8

"""
    Yapily API

    The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.

    The version of the OpenAPI document: 4.2.0
    Contact: support@yapily.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import re  # noqa: F401

from aenum import Enum


class AccountBalanceType(str, Enum):
    """
    Specifies the type of the stated account balance.
    """

    """
    allowed enum values
    """
    CLOSING_AVAILABLE = 'CLOSING_AVAILABLE'
    CLOSING_BOOKED = 'CLOSING_BOOKED'
    CLOSING_CLEARED = 'CLOSING_CLEARED'
    EXPECTED = 'EXPECTED'
    FORWARD_AVAILABLE = 'FORWARD_AVAILABLE'
    INFORMATION = 'INFORMATION'
    INTERIM_AVAILABLE = 'INTERIM_AVAILABLE'
    INTERIM_BOOKED = 'INTERIM_BOOKED'
    INTERIM_CLEARED = 'INTERIM_CLEARED'
    OPENING_AVAILABLE = 'OPENING_AVAILABLE'
    OPENING_BOOKED = 'OPENING_BOOKED'
    OPENING_CLEARED = 'OPENING_CLEARED'
    PREVIOUSLY_CLOSED_BOOKED = 'PREVIOUSLY_CLOSED_BOOKED'
    AUTHORISED = 'AUTHORISED'
    OTHER = 'OTHER'
    UNKNOWN = 'UNKNOWN'

    @classmethod
    def from_json(cls, json_str: str) -> "AccountBalanceType":
        """Create an instance of AccountBalanceType from a JSON string"""
        return AccountBalanceType(json.loads(json_str))


