from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AuthorisationStatus(str, Enum):
    """
    allowed enum values
    """

    AWAITING_AUTHORIZATION = "AWAITING_AUTHORIZATION"
    AWAITING_FURTHER_AUTHORIZATION = "AWAITING_FURTHER_AUTHORIZATION"
    AWAITING_RE_AUTHORIZATION = "AWAITING_RE_AUTHORIZATION"
    AUTHORIZED = "AUTHORIZED"
    CONSUMED = "CONSUMED"
    REJECTED = "REJECTED"
    REVOKED = "REVOKED"
    FAILED = "FAILED"
    EXPIRED = "EXPIRED"
    UNKNOWN = "UNKNOWN"
    INVALID = "INVALID"
    AWAITING_DECOUPLED_PRE_AUTHORIZATION = "AWAITING_DECOUPLED_PRE_AUTHORIZATION"
    AWAITING_PRE_AUTHORIZATION = "AWAITING_PRE_AUTHORIZATION"
    PRE_AUTHORIZED = "PRE_AUTHORIZED"
    AWAITING_DECOUPLED_AUTHORIZATION = "AWAITING_DECOUPLED_AUTHORIZATION"
    AWAITING_SCA_METHOD = "AWAITING_SCA_METHOD"
    AWAITING_SCA_CODE = "AWAITING_SCA_CODE"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        return cls(json.loads(json_str))
