# coding: utf-8

"""
Yapily API

The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.

The version of the OpenAPI document: 7.2.0
Contact: support@yapily.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from pydantic import BaseModel, Field, StrictStr
from yapily.models.notification import Notification


class EventSubscriptionResponse(BaseModel):
    """
    EventSubscriptionResponse
    """

    event_type_id: StrictStr = Field(
        default=...,
        alias="eventTypeId",
        description="Unique identifier of the event type (for which notifications will be sent)",
    )
    application_id: StrictStr = Field(
        default=...,
        alias="applicationId",
        description="Application related to event subscription.",
    )
    created: StrictStr = Field(
        default=..., description="Creation date of event subscription."
    )
    notification: Notification = Field(...)
    __properties = ["eventTypeId", "applicationId", "created", "notification"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> EventSubscriptionResponse:
        """Create an instance of EventSubscriptionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of notification
        if self.notification:
            _dict["notification"] = self.notification.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> EventSubscriptionResponse:
        """Create an instance of EventSubscriptionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return EventSubscriptionResponse.parse_obj(obj)

        _obj = EventSubscriptionResponse.parse_obj(
            {
                "event_type_id": obj.get("eventTypeId"),
                "application_id": obj.get("applicationId"),
                "created": obj.get("created"),
                "notification": Notification.from_dict(obj.get("notification"))
                if obj.get("notification") is not None
                else None,
            }
        )
        return _obj
