from typing import Annotated
"""
Yapily API

The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.

The version of the OpenAPI document: 7.2.0
Contact: support@yapily.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr

from yapily.models.sort_enum import SortEnum


class FilterAndSort(BaseModel):
    """
    FilterAndSort
    """

    var_from: Annotated[datetime | None, Field(alias='from', description='__Optional__. The earliest date and time of resources / records that should be returned.')] = None
    before: Annotated[datetime | None, Field(description='__Optional__. The latest date and time of resources / records that should be returned.')] = None
    limit: Annotated[StrictInt | None, Field(description='__Optional__. The maximum number of resources / records that should be returned.')] = None
    sort: SortEnum | None = None
    offset: StrictInt | None = None
    cursor: StrictStr | None = None
    __properties = ["from", "before", "limit", "sort", "offset", "cursor"]
    model_config = ConfigDict(populate_by_name=True, validate_assignment=True)

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> FilterAndSort:
        """Create an instance of FilterAndSort from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        return self.dict(by_alias=True, exclude={}, exclude_none=True)

    @classmethod
    def from_dict(cls, obj: dict) -> FilterAndSort:
        """Create an instance of FilterAndSort from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return FilterAndSort.parse_obj(obj)

        return FilterAndSort.parse_obj(
            {
                "var_from": obj.get("from"),
                "before": obj.get("before"),
                "limit": obj.get("limit"),
                "sort": obj.get("sort"),
                "offset": obj.get("offset"),
                "cursor": obj.get("cursor"),
            }
        )
