from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PaymentType(str, Enum):
    """
    allowed enum values
    """

    DOMESTIC_PAYMENT = "DOMESTIC_PAYMENT"
    DOMESTIC_INSTANT_PAYMENT = "DOMESTIC_INSTANT_PAYMENT"
    DOMESTIC_VARIABLE_RECURRING_PAYMENT = "DOMESTIC_VARIABLE_RECURRING_PAYMENT"
    DOMESTIC_SCHEDULED_PAYMENT = "DOMESTIC_SCHEDULED_PAYMENT"
    DOMESTIC_PERIODIC_PAYMENT = "DOMESTIC_PERIODIC_PAYMENT"
    INTERNATIONAL_PAYMENT = "INTERNATIONAL_PAYMENT"
    INTERNATIONAL_SCHEDULED_PAYMENT = "INTERNATIONAL_SCHEDULED_PAYMENT"
    INTERNATIONAL_PERIODIC_PAYMENT = "INTERNATIONAL_PERIODIC_PAYMENT"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        return cls(json.loads(json_str))
